package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Tuesday, 29 April, 2025 2:00:08 AM IST
*/

public interface ReverseOperations 
{
  String reverseString (String str);
} // interface ReverseOperations
